spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: bob
    password: bobpw
    driver-class-name: oracle.jdbc.driver.OracleDriver

  messages:
    basename: messages,errors

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*
    cache: false

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

mybatis:
  mapper-locations: /mappings/mapper/*.xml

#logging.level.org.apache.coyote.http11:
#  debug